### ISSUE TITLE
Using experiment date format (YYYY-MM-DD) triggers alert

### ISSUE THREAD

**Issue by coltonlloyd** [SBRG/experiment_metadata#28]
This code block doesn't check for the recommended format when loading a batch sample spreadsheet

https://github.com/SBRG/experiment_metadata/blob/5a53b9b8c16fa5c80228ff1bc6b6a49376d5faa3/main.js#L606

**Comment by pvphaneuf** [comment]
c2a0f68b2e40e3358711f5d7c60e3368953745df
